version: '3'
services:
    app:
        build:
            context: ./docker/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: ''${WWWGROUP}'
        image: app
        ports:
            - '9000:9000'
        environment:
            WWWUSER: '${WWWUSER}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
    nginx:
        image: nginx:1.21.1
        ports:
        - "80:80"
        volumes:
        - '.:/var/www/html'
        - ./docker/8.0/nginx.conf:/etc/nginx/conf.d/blog.com.conf
        restart: always
        networks:
            - sail
        depends_on:
            - app
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s
    redis:
        image: 'redis:alpine'
        ports: 
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes: 
            - 'sailredis:/var/lib/redis'
        networks: 
            - sail
        healthcheck:
          test: ['CMD', 'redis-cli', 'ping']
          retries: 3
          timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
